package com.android.systemui.Biftor;

import android.content.Context;
import android.provider.Settings.System;

public class BiftorSettings {
    public static String DropDownHeaderBackgroundString;
    public static String NaviBackgroundString;
    public static String StatusBarBackgroundString;
    public static int mAllColor;
    public static int mBatteryIconLocation;
    public static int mBiftorBatteryIconChargeBattTextColor;
    public static int mBiftorBatteryIconColor;
    public static int mBiftorBatteryIconLowBattTextColor;
    public static int mBiftorBatteryIconTextColor;
    public static int mBiftorBatteryIconlocation;
    public static int mBiftorBatteryIcontype;
    public static String mBiftorCloseDragHandBackgroundString;
    public static int mBiftorCloseDragHandleBGType;
    public static int mBiftorCloseDragHandleBGcolor;
    public static int mBiftorCloseDragHandleGradientBackGroundCornerRadius;
    public static int mBiftorCloseDragHandleGradientBackGroundModel;
    public static int mBiftorCloseDragHandleGradientBackGroundRadius;
    public static int mBiftorCloseDragHandleGradientBackGroundType;
    public static int mBiftorCloseDragHandleGradientColor1;
    public static int mBiftorCloseDragHandleGradientColor2;
    public static int mBiftorCloseDragHandleGradientColor3;
    public static int mBiftorCloseDragHandleGradientEnable3Color;
    public static int mBiftorCloseDragHandleWallpapercolor;
    public static int mBiftorDefaultColor = -1;
    public static int mBiftorDefaultIntforNull = 420889142;
    public static int mBiftorDropDownCarrierLableColor;
    public static int mBiftorDropDownClockColor;
    public static int mBiftorDropDownDateColor;
    public static int mBiftorDropDownHeaderBGColor;
    public static int mBiftorDropDownHeaderBGType;
    public static int mBiftorDropDownHeaderButtonColor;
    public static int mBiftorDropDownHeaderGradientBackGroundCornerRadius;
    public static int mBiftorDropDownHeaderGradientBackGroundModel;
    public static int mBiftorDropDownHeaderGradientBackGroundRadius;
    public static int mBiftorDropDownHeaderGradientBackGroundType;
    public static int mBiftorDropDownHeaderGradientColor1;
    public static int mBiftorDropDownHeaderGradientColor2;
    public static int mBiftorDropDownHeaderGradientColor3;
    public static int mBiftorDropDownHeaderGradientEnable3Color;
    public static int mBiftorDropDownHeaderwallpapercolor;
    public static int mBiftorDropDownSlideShowAnimationDuration;
    public static int mBiftorDropDownSlideShowAnimationType;
    public static int mBiftorDropDownSlideShowEffectAnimationDuration;
    public static int mBiftorDropDownSlideShowEffectAnimationType;
    public static String mBiftorDropDownSlideShowEffectMusic;
    public static int mBiftorDropDownSlideShowEffectPlayAnimationButtonColor;
    public static int mBiftorDropDownSlideShowEffectScreenOn;
    public static String mBiftorDropDownSlideShowEffectWallpaper;
    public static String mBiftorDropDownSlideShowWallpaper;
    public static int mBiftorEnableDropDownSlideShow;
    public static int mBiftorEnableDropDownSlideShowEffect;
    public static int mBiftorEnableDropDownSlideShowEffectFullScreen;
    public static int mBiftorEnableDropDownSlideShowEffectMusic;
    public static int mBiftorEnableGradientCloseDragHandleBG;
    public static int mBiftorEnableGradientDropDownHeader;
    public static int mBiftorEnableGradientNaviBG;
    public static int mBiftorEnableGradientSHCNormalBG;
    public static int mBiftorEnableGradientSHCPressBG;
    public static int mBiftorEnableGradientStatusBarBG;
    public static int mBiftorEnableGradientTileNormalBG;
    public static int mBiftorEnableGradientTilePressBG;
    public static int mBiftorEnableLoopDropDownSlideShowEffectMusic;
    public static int mBiftorEnableSignalTextSize;
    public static int mBiftorInternetSpeedAlignment;
    public static int mBiftorInternetSpeedColor;
    public static int mBiftorInternetSpeedLogoColor;
    public static int mBiftorInternetSpeedSize;
    public static int mBiftorInternetSpeedUpdateTime;
    public static int mBiftorNaviBGType;
    public static int mBiftorNaviBGcolor;
    public static int mBiftorNaviGradientBackGroundCornerRadius;
    public static int mBiftorNaviGradientBackGroundModel;
    public static int mBiftorNaviGradientBackGroundRadius;
    public static int mBiftorNaviGradientBackGroundType;
    public static int mBiftorNaviGradientColor1;
    public static int mBiftorNaviGradientColor2;
    public static int mBiftorNaviGradientColor3;
    public static int mBiftorNaviGradientEnable3Color;
    public static int mBiftorNaviwallpapercolor;
    public static int mBiftorRecentPanelBGColor;
    public static int mBiftorRecentPanelBTNColor;
    public static int mBiftorRecentPanelWClBGColor;
    public static int mBiftorRecentPanelwallpapercolor;
    public static int mBiftorSHCBGAlpha;
    public static int mBiftorSHCBGDiv;
    public static int mBiftorSHCBGType;
    public static String mBiftorSHCConfig;
    public static int mBiftorSHCEnableIconColor;
    public static int mBiftorSHCEnableTextColor;
    public static int mBiftorSHCIconColor;
    public static int mBiftorSHCNormalBG;
    public static String mBiftorSHCNormalBackgroundString;
    public static int mBiftorSHCNormalGradientBackGroundCornerRadius;
    public static int mBiftorSHCNormalGradientBackGroundModel;
    public static int mBiftorSHCNormalGradientBackGroundRadius;
    public static int mBiftorSHCNormalGradientBackGroundType;
    public static int mBiftorSHCNormalGradientColor1;
    public static int mBiftorSHCNormalGradientColor2;
    public static int mBiftorSHCNormalGradientColor3;
    public static int mBiftorSHCNormalGradientEnable3Color;
    public static int mBiftorSHCNormalWallpapercolor;
    public static int mBiftorSHCPressBG;
    public static String mBiftorSHCPressBackgroundString;
    public static int mBiftorSHCPressGradientBackGroundCornerRadius;
    public static int mBiftorSHCPressGradientBackGroundModel;
    public static int mBiftorSHCPressGradientBackGroundRadius;
    public static int mBiftorSHCPressGradientBackGroundType;
    public static int mBiftorSHCPressGradientColor1;
    public static int mBiftorSHCPressGradientColor2;
    public static int mBiftorSHCPressGradientColor3;
    public static int mBiftorSHCPressGradientEnable3Color;
    public static int mBiftorSHCPressWallpapercolor;
    public static int mBiftorSHCShowDiv;
    public static int mBiftorSHCShowText;
    public static int mBiftorSHCTextColor;
    public static int mBiftorShowHaloBTN;
    public static int mBiftorShowInternetSpeed;
    public static int mBiftorShowSignalDBM;
    public static int mBiftorSignalDBMColor;
    public static int mBiftorSignalIconStrength;
    public static int mBiftorSignalTextColor;
    public static int mBiftorSignalTextLocation;
    public static int mBiftorSignalTextSize;
    public static int mBiftorStatusBarBGType;
    public static int mBiftorStatusBarGradientBackGroundCornerRadius;
    public static int mBiftorStatusBarGradientBackGroundModel;
    public static int mBiftorStatusBarGradientBackGroundRadius;
    public static int mBiftorStatusBarGradientBackGroundType;
    public static int mBiftorStatusBarGradientColor1;
    public static int mBiftorStatusBarGradientColor2;
    public static int mBiftorStatusBarGradientColor3;
    public static int mBiftorStatusBarGradientEnable3Color;
    public static int mBiftorStatusBarwallpapercolor;
    public static int mBiftorTileBGType;
    public static String mBiftorTileNormalBackgroundString;
    public static int mBiftorTileNormalGradientBackGroundCornerRadius;
    public static int mBiftorTileNormalGradientBackGroundModel;
    public static int mBiftorTileNormalGradientBackGroundRadius;
    public static int mBiftorTileNormalGradientBackGroundType;
    public static int mBiftorTileNormalGradientColor1;
    public static int mBiftorTileNormalGradientColor2;
    public static int mBiftorTileNormalGradientColor3;
    public static int mBiftorTileNormalGradientEnable3Color;
    public static int mBiftorTileNormalWallpapercolor;
    public static String mBiftorTilePressBackgroundString;
    public static int mBiftorTilePressGradientBackGroundCornerRadius;
    public static int mBiftorTilePressGradientBackGroundModel;
    public static int mBiftorTilePressGradientBackGroundRadius;
    public static int mBiftorTilePressGradientBackGroundType;
    public static int mBiftorTilePressGradientColor1;
    public static int mBiftorTilePressGradientColor2;
    public static int mBiftorTilePressGradientColor3;
    public static int mBiftorTilePressGradientEnable3Color;
    public static int mBiftorTilePressWallpapercolor;
    public static int mBiftorstatusbarAirplaneColor;
    public static int mBiftorstatusbarBGcolor;
    public static int mBiftorstatusbarMobileDataColor;
    public static int mBiftorstatusbarSignalColor;
    public static int mBiftorstatusbarTickerColor;
    public static int mBiftorstatusbarWifiColor;
    public static int mBiftortoggleCloseDragHandleWallpapercolor;
    public static int mBiftortoggleDropDownHeaderwallpapercolor;
    public static int mBiftortoggleNaviwallpapercolor;
    public static int mBiftortoggleRecentPanelwallpapercolor;
    public static int mBiftortoggleSHCNormalWallpapercolor;
    public static int mBiftortoggleSHCPressWallpapercolor;
    public static int mBiftortoggleStatusBarwallpapercolor;
    public static int mBiftortoggleTileNormalWallpapercolor;
    public static int mBiftortoggleTilePressWallpapercolor;
    public static Context mContext;
    public static int mEnableAllColor;
    public static int mEnableBiftorInternetSpeedSize;
    public static int mEnableBiftorQuickLunchCollapsePanels;
    public static int mEnableBiftorQuickLunchPanel;
    public static int mEnableBiftorQuickLunchScroll;
    public static int mEnableBiftorQuickLunchVib;
    public static int mEnableRandomColor;
    public static int mEnableRecentPanelClearAllBTN;
    public static int mEnableStatusBarExtraColor;
    public static int mHideAlarm;
    public static int mHideBluetooth;
    public static int mHideVolume;
    public static String mLoClockClick;
    public static String mLoDateClick;
    public static int mRandomColor;
    public static String mRecentPanelBackgroundString;
    public static int mRotationSignal;
    public static String mShClockClick;
    public static String mShDateClick;
    public static int mSignalIconLocation;

    public static void Biftor_Get_All_Settings(Context context) {
        mContext = context;
        mEnableRandomColor = System.getInt(mContext.getContentResolver(), "toggle_Biftor_random_color", 0);
        mRandomColor = System.getInt(mContext.getContentResolver(), "Biftor_random_color", mBiftorDefaultColor);
        mEnableAllColor = System.getInt(mContext.getContentResolver(), "toggle_all_phone_text_color", 0);
        mAllColor = System.getInt(mContext.getContentResolver(), "all_phone_text_color", mBiftorDefaultColor);
        mEnableStatusBarExtraColor = System.getInt(mContext.getContentResolver(), "Biftor_Enable_STB_Extra_color", 0);
        mBiftorstatusbarWifiColor = System.getInt(mContext.getContentResolver(), "Biftor_statusbar_Wifi_color", mBiftorDefaultColor);
        mBiftorstatusbarSignalColor = System.getInt(mContext.getContentResolver(), "Biftor_statusbar_Signal_color", mBiftorDefaultColor);
        mBiftorstatusbarMobileDataColor = System.getInt(mContext.getContentResolver(), "Biftor_statusbar_Mobile_Data_color", mBiftorDefaultColor);
        mBiftorstatusbarAirplaneColor = System.getInt(mContext.getContentResolver(), "Biftor_statusbar_Airplane_color", mBiftorDefaultColor);
        mBiftorstatusbarTickerColor = System.getInt(mContext.getContentResolver(), "Biftor_statusbar_Ticker_color", mBiftorDefaultColor);
        mBiftorDropDownCarrierLableColor = System.getInt(mContext.getContentResolver(), "Biftor_DropDown_Carrier_Lable_color", mBiftorDefaultColor);
        mBiftorDropDownHeaderButtonColor = System.getInt(mContext.getContentResolver(), "Biftor_DropDown_Header_Button_color", mBiftorDefaultColor);
        mBiftorDropDownDateColor = System.getInt(mContext.getContentResolver(), "Biftor_DropDown_Date_color", mBiftorDefaultColor);
        mBiftorDropDownClockColor = System.getInt(mContext.getContentResolver(), "Biftor_DropDown_Clock_color", mBiftorDefaultColor);
        mBiftorstatusbarBGcolor = System.getInt(mContext.getContentResolver(), "Biftor_statusbar_BG_color", -16777216);
        mBiftorStatusBarBGType = System.getInt(mContext.getContentResolver(), "Biftor_StatusBar_BG_Type", 1);
        mBiftorEnableGradientStatusBarBG = System.getInt(mContext.getContentResolver(), "Biftor_Enable_Gradient_StatusBar_BG", 0);
        mBiftorStatusBarGradientColor1 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color1_StatusBar_BG", -1);
        mBiftorStatusBarGradientColor2 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color2_StatusBar_BG", -16777216);
        mBiftorStatusBarGradientColor3 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color3_StatusBar_BG", -1);
        mBiftorStatusBarGradientBackGroundType = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_StatusBar_BG_Type", 1);
        mBiftorStatusBarGradientBackGroundModel = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Model_StatusBar_BG_Type", 0);
        mBiftorStatusBarGradientBackGroundRadius = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Radius_StatusBar_BG", 360);
        mBiftorStatusBarGradientBackGroundCornerRadius = System.getInt(mContext.getContentResolver(), "Biftor_Corner_Radius_StatusBar_BG", 0);
        mBiftorStatusBarGradientEnable3Color = System.getInt(mContext.getContentResolver(), "Biftor_Enable_Gradient_3Color_StatusBar_BG", 0);
        mBiftorDropDownHeaderBGType = System.getInt(mContext.getContentResolver(), "Biftor_DropDownHeader_BG_Type", 1);
        mBiftorDropDownHeaderBGColor = System.getInt(mContext.getContentResolver(), "Biftor_DropDown_Header_BG_Color", -16777216);
        mBiftorEnableGradientDropDownHeader = System.getInt(mContext.getContentResolver(), "Biftor_Enable_Gradient_DropDownHeader_BG", 0);
        mBiftorDropDownHeaderGradientColor1 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color1_DropDownHeader_BG", -1);
        mBiftorDropDownHeaderGradientColor2 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color2_DropDownHeader_BG", -16777216);
        mBiftorDropDownHeaderGradientColor3 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color3_DropDownHeader_BG", -1);
        mBiftorDropDownHeaderGradientBackGroundType = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_DropDownHeader_BG_Type", 1);
        mBiftorDropDownHeaderGradientBackGroundModel = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Model_DropDownHeader_BG_Type", 0);
        mBiftorDropDownHeaderGradientBackGroundRadius = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Radius_DropDownHeader_BG", 360);
        mBiftorDropDownHeaderGradientBackGroundCornerRadius = System.getInt(mContext.getContentResolver(), "Biftor_Corner_Radius_DropDownHeader_BG", 0);
        mBiftorDropDownHeaderGradientEnable3Color = System.getInt(mContext.getContentResolver(), "Biftor_Enable_Gradient_3Color_DropDownHeader_BG", 0);
        mShClockClick = System.getString(mContext.getContentResolver(), "SH_Picker_Biftor_Header_Clock_SHclick");
        mLoClockClick = System.getString(mContext.getContentResolver(), "SH_Picker_Biftor_Header_Clock_LGclick");
        mShDateClick = System.getString(mContext.getContentResolver(), "SH_Picker_Biftor_Header_Date_SHclick");
        mLoDateClick = System.getString(mContext.getContentResolver(), "SH_Picker_Biftor_Header_Date_LGclick");
        mBiftorSHCConfig = System.getString(mContext.getContentResolver(), "Biftor_SHC_Config");
        mBiftorSHCNormalBG = System.getInt(mContext.getContentResolver(), "Biftor_SHCNormal_BG_Color", -14606047);
        mBiftorSHCPressBG = System.getInt(mContext.getContentResolver(), "Biftor_SHCPress_BG_Color", -15329770);
        mBiftorSHCTextColor = System.getInt(mContext.getContentResolver(), "Biftor_SHCText_Color", mBiftorDefaultColor);
        mBiftorSHCIconColor = System.getInt(mContext.getContentResolver(), "Biftor_SHCIcon_Color", mBiftorDefaultColor);
        mBiftorSHCBGAlpha = System.getInt(mContext.getContentResolver(), "Biftor_SHC_BG_Alpha", 120);
        mBiftorSHCBGDiv = System.getInt(mContext.getContentResolver(), "Biftor_SHC_BG_Divider", 0);
        mBiftorSHCBGType = System.getInt(mContext.getContentResolver(), "Biftor_SHCNormal_BG_Type", 1);
        mBiftorEnableGradientSHCNormalBG = System.getInt(mContext.getContentResolver(), "Biftor_Enable_Gradient_SHCNormal_BG", 0);
        mBiftorSHCNormalGradientColor1 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color1_SHCNormal_BG", -1);
        mBiftorSHCNormalGradientColor2 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color2_SHCNormal_BG", -16777216);
        mBiftorSHCNormalGradientColor3 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color3_SHCNormal_BG", -1);
        mBiftorSHCNormalGradientBackGroundType = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_SHCNormal_BG_Type", 1);
        mBiftorSHCNormalGradientBackGroundModel = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Model_SHCNormal_BG_Type", 0);
        mBiftorSHCNormalGradientBackGroundRadius = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Radius_SHCNormal_BG", 360);
        mBiftorSHCNormalGradientBackGroundCornerRadius = System.getInt(mContext.getContentResolver(), "Biftor_Corner_Radius_SHCNormal_BG", 0);
        mBiftorSHCNormalGradientEnable3Color = System.getInt(mContext.getContentResolver(), "Biftor_Enable_Gradient_3Color_SHCNormal_BG", 0);
        mBiftorSHCNormalBackgroundString = System.getString(mContext.getContentResolver(), "Biftor_SHCNormal_BG");
        mBiftortoggleSHCNormalWallpapercolor = System.getInt(mContext.getContentResolver(), "Biftor_toggle_SHCNormalWallpaper_color", 0);
        mBiftorSHCNormalWallpapercolor = System.getInt(mContext.getContentResolver(), "Biftor_SHCNormalWallpaper_color", 153);
        mBiftorEnableGradientSHCPressBG = System.getInt(mContext.getContentResolver(), "Biftor_Enable_Gradient_SHCPress_BG", 0);
        mBiftorSHCPressGradientColor1 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color1_SHCPress_BG", -1);
        mBiftorSHCPressGradientColor2 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color2_SHCPress_BG", -16777216);
        mBiftorSHCPressGradientColor3 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color3_SHCPress_BG", -1);
        mBiftorSHCPressGradientBackGroundType = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_SHCPress_BG_Type", 1);
        mBiftorSHCPressGradientBackGroundModel = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Model_SHCPress_BG_Type", 0);
        mBiftorSHCPressGradientBackGroundRadius = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Radius_SHCPress_BG", 360);
        mBiftorSHCPressGradientBackGroundCornerRadius = System.getInt(mContext.getContentResolver(), "Biftor_Corner_Radius_SHCPress_BG", 0);
        mBiftorSHCPressGradientEnable3Color = System.getInt(mContext.getContentResolver(), "Biftor_Enable_Gradient_3Color_SHCPress_BG", 0);
        mBiftorSHCPressBackgroundString = System.getString(mContext.getContentResolver(), "Biftor_SHCPress_BG");
        mBiftortoggleSHCPressWallpapercolor = System.getInt(mContext.getContentResolver(), "Biftor_toggle_SHCPressWallpaper_color", 0);
        mBiftorSHCPressWallpapercolor = System.getInt(mContext.getContentResolver(), "Biftor_SHCPressWallpaper_color", 153);
        mBiftorSHCShowDiv = System.getInt(mContext.getContentResolver(), "Biftor_SHC_Show_Divider", 1);
        mBiftorSHCShowText = System.getInt(mContext.getContentResolver(), "Biftor_SHC_Show_Text", 1);
        mBiftorSHCEnableTextColor = System.getInt(mContext.getContentResolver(), "Biftor_SHC_Enable_Text_Color", 0);
        mBiftorSHCEnableIconColor = System.getInt(mContext.getContentResolver(), "Biftor_SHC_Enable_Icon_Color", 0);
        mEnableBiftorQuickLunchPanel = System.getInt(mContext.getContentResolver(), "Enable_Biftor_Quick_Lunch_Panel", 0);
        mEnableBiftorQuickLunchCollapsePanels = System.getInt(mContext.getContentResolver(), "Enable_Biftor_CollapsePanels", 1);
        mEnableBiftorQuickLunchVib = System.getInt(mContext.getContentResolver(), "Enable_Biftor_QuickLunch_Vib", 1);
        mEnableBiftorQuickLunchScroll = System.getInt(mContext.getContentResolver(), "Enable_Biftor_QuickLunch_Scroll", 0);
        StatusBarBackgroundString = System.getString(mContext.getContentResolver(), "Biftor_StatusBar_BG");
        DropDownHeaderBackgroundString = System.getString(mContext.getContentResolver(), "Biftor_DropDownHeader_BG");
        mBiftortoggleStatusBarwallpapercolor = System.getInt(mContext.getContentResolver(), "Biftor_toggle_StatusBarwallpaper_color", 0);
        mBiftorStatusBarwallpapercolor = System.getInt(mContext.getContentResolver(), "Biftor_StatusBarwallpaper_color", 153);
        mBiftortoggleDropDownHeaderwallpapercolor = System.getInt(mContext.getContentResolver(), "Biftor_toggle_DropDownHeaderwallpaper_color", 0);
        mBiftorDropDownHeaderwallpapercolor = System.getInt(mContext.getContentResolver(), "Biftor_DropDownHeaderwallpaper_color", 153);
        mSignalIconLocation = System.getInt(mContext.getContentResolver(), "Biftor_Signal_Icon_Location", 1);
        mBatteryIconLocation = System.getInt(mContext.getContentResolver(), "Biftor_Battery_Icon_Location", 1);
        mRotationSignal = System.getInt(mContext.getContentResolver(), "Biftor_Rotation_Signal_Icon", 0);
        mHideAlarm = System.getInt(mContext.getContentResolver(), "Hide_alarm_clock", 0);
        mHideVolume = System.getInt(mContext.getContentResolver(), "Hide_volume_icon", 0);
        mHideBluetooth = System.getInt(mContext.getContentResolver(), "Hide_bluetooth_icon", 0);
        mBiftorSignalIconStrength = System.getInt(mContext.getContentResolver(), "Biftor_Signal_Icon_Strength", 1);
        mBiftorShowHaloBTN = System.getInt(mContext.getContentResolver(), "Biftor_Show_HaloBTN", 1);
        mBiftorShowInternetSpeed = System.getInt(mContext.getContentResolver(), "Biftor_Show_StatusBar_InternetSpeed", 0);
        mBiftorInternetSpeedAlignment = System.getInt(mContext.getContentResolver(), "Biftor_StatusBar_InternetSpeed_Alignment", 1);
        mBiftorInternetSpeedColor = System.getInt(mContext.getContentResolver(), "Biftor_StatusBar_InternetSpeed_color", mBiftorDefaultColor);
        mBiftorInternetSpeedLogoColor = System.getInt(mContext.getContentResolver(), "Biftor_StatusBar_InternetSpeed_Logo_color", mBiftorDefaultColor);
        mEnableBiftorInternetSpeedSize = System.getInt(mContext.getContentResolver(), "Biftor_Enable_StatusBar_InternetSpeed_Size", 0);
        mBiftorInternetSpeedSize = System.getInt(mContext.getContentResolver(), "Biftor_StatusBar_InternetSpeed_Size", 13);
        mBiftorInternetSpeedUpdateTime = System.getInt(mContext.getContentResolver(), "Biftor_StatusBar_InternetSpeed_UpdateTime", 500);
        mBiftorSignalTextLocation = System.getInt(mContext.getContentResolver(), "Biftor_StatusBar_Signaltext_Alignment", 5);
        mBiftorEnableSignalTextSize = System.getInt(mContext.getContentResolver(), "Biftor_Enable_StatusBar_Signaltext_Size", 0);
        mBiftorSignalTextSize = System.getInt(mContext.getContentResolver(), "Biftor_StatusBar_Signaltext_Size", 14);
        mBiftorSignalTextColor = System.getInt(mContext.getContentResolver(), "Biftor_StatusBar_Signaltext_Color", mBiftorDefaultColor);
        mBiftorSignalDBMColor = System.getInt(mContext.getContentResolver(), "Biftor_StatusBar_DBM_Color", mBiftorDefaultColor);
        mBiftorShowSignalDBM = System.getInt(mContext.getContentResolver(), "Biftor_Show_StatusBar_DBM", 1);
        mBiftorRecentPanelBTNColor = System.getInt(mContext.getContentResolver(), "Biftor_Recent_Panel_BTN_Color", mBiftorDefaultColor);
        mBiftorRecentPanelBGColor = System.getInt(mContext.getContentResolver(), "Biftor_Recent_Panel_BG_Color", -1426063361);
        mBiftorRecentPanelWClBGColor = System.getInt(mContext.getContentResolver(), "Biftor_Recent_Panel_WCl_BG_Color", -1426128896);
        mBiftortoggleRecentPanelwallpapercolor = System.getInt(mContext.getContentResolver(), "Biftor_toggle_RecentPanelwallpaper_color", 0);
        mBiftorRecentPanelwallpapercolor = System.getInt(mContext.getContentResolver(), "Biftor_RecentPanelwallpaper_color", 153);
        mRecentPanelBackgroundString = System.getString(mContext.getContentResolver(), "Biftor_RecentPanel_BG");
        mEnableRecentPanelClearAllBTN = System.getInt(mContext.getContentResolver(), "Biftor_Enable_RecentPanel_ClearAll_BTN", 0);
        mBiftorCloseDragHandleBGType = System.getInt(mContext.getContentResolver(), "Biftor_CloseDragHandle_BG_Type", 1);
        mBiftorCloseDragHandleBGcolor = System.getInt(mContext.getContentResolver(), "Biftor_CloseDragHandle_BG_Color", -1);
        mBiftorEnableGradientCloseDragHandleBG = System.getInt(mContext.getContentResolver(), "Biftor_Enable_Gradient_CloseDragHandle_BG", 0);
        mBiftorCloseDragHandleGradientColor1 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color1_CloseDragHandle_BG", -1);
        mBiftorCloseDragHandleGradientColor2 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color2_CloseDragHandle_BG", -16777216);
        mBiftorCloseDragHandleGradientColor3 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color3_CloseDragHandle_BG", -1);
        mBiftorCloseDragHandleGradientBackGroundType = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_CloseDragHandle_BG_Type", 1);
        mBiftorCloseDragHandleGradientBackGroundModel = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Model_CloseDragHandle_BG_Type", 0);
        mBiftorCloseDragHandleGradientBackGroundRadius = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Radius_CloseDragHandle_BG", 360);
        mBiftorCloseDragHandleGradientBackGroundCornerRadius = System.getInt(mContext.getContentResolver(), "Biftor_Corner_Radius_CloseDragHandle_BG", 0);
        mBiftorCloseDragHandleGradientEnable3Color = System.getInt(mContext.getContentResolver(), "Biftor_Enable_Gradient_3Color_CloseDragHandle_BG", 0);
        mBiftorCloseDragHandBackgroundString = System.getString(mContext.getContentResolver(), "Biftor_Close_Drag_Handel_BG");
        mBiftortoggleCloseDragHandleWallpapercolor = System.getInt(mContext.getContentResolver(), "Biftor_toggle_CloseDragHandleWallpaper_color", 0);
        mBiftorCloseDragHandleWallpapercolor = System.getInt(mContext.getContentResolver(), "Biftor_CloseDragHandleWallpaper_color", 153);
        mBiftorTileBGType = System.getInt(mContext.getContentResolver(), "Biftor_TileNormal_BG_Type", 1);
        mBiftorEnableGradientTileNormalBG = System.getInt(mContext.getContentResolver(), "Biftor_Enable_Gradient_TileNormal_BG", 0);
        mBiftorTileNormalGradientColor1 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color1_TileNormal_BG", -1);
        mBiftorTileNormalGradientColor2 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color2_TileNormal_BG", -16777216);
        mBiftorTileNormalGradientColor3 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color3_TileNormal_BG", -1);
        mBiftorTileNormalGradientBackGroundType = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_TileNormal_BG_Type", 1);
        mBiftorTileNormalGradientBackGroundModel = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Model_TileNormal_BG_Type", 0);
        mBiftorTileNormalGradientBackGroundRadius = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Radius_TileNormal_BG", 360);
        mBiftorTileNormalGradientBackGroundCornerRadius = System.getInt(mContext.getContentResolver(), "Biftor_Corner_Radius_TileNormal_BG", 0);
        mBiftorTileNormalGradientEnable3Color = System.getInt(mContext.getContentResolver(), "Biftor_Enable_Gradient_3Color_TileNormal_BG", 0);
        mBiftorTileNormalBackgroundString = System.getString(mContext.getContentResolver(), "Biftor_TileNormal_bg");
        mBiftortoggleTileNormalWallpapercolor = System.getInt(mContext.getContentResolver(), "Biftor_toggle_TileNormalWallpaper_color", 0);
        mBiftorTileNormalWallpapercolor = System.getInt(mContext.getContentResolver(), "Biftor_TileNormalWallpaper_color", 153);
        mBiftorEnableGradientTilePressBG = System.getInt(mContext.getContentResolver(), "Biftor_Enable_Gradient_TilePress_BG", 0);
        mBiftorTilePressGradientColor1 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color1_TilePress_BG", -1);
        mBiftorTilePressGradientColor2 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color2_TilePress_BG", -16777216);
        mBiftorTilePressGradientColor3 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color3_TilePress_BG", -1);
        mBiftorTilePressGradientBackGroundType = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_TilePress_BG_Type", 1);
        mBiftorTilePressGradientBackGroundModel = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Model_TilePress_BG_Type", 0);
        mBiftorTilePressGradientBackGroundRadius = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Radius_TilePress_BG", 360);
        mBiftorTilePressGradientBackGroundCornerRadius = System.getInt(mContext.getContentResolver(), "Biftor_Corner_Radius_TilePress_BG", 0);
        mBiftorTilePressGradientEnable3Color = System.getInt(mContext.getContentResolver(), "Biftor_Enable_Gradient_3Color_TilePress_BG", 0);
        mBiftorTilePressBackgroundString = System.getString(mContext.getContentResolver(), "Biftor_TilePress_bg");
        mBiftortoggleTilePressWallpapercolor = System.getInt(mContext.getContentResolver(), "Biftor_toggle_TilePressWallpaper_color", 0);
        mBiftorTilePressWallpapercolor = System.getInt(mContext.getContentResolver(), "Biftor_TilePressWallpaper_color", 153);
        mBiftorBatteryIcontype = System.getInt(mContext.getContentResolver(), "Biftor_Battery_Icon_Type", 0);
        mBiftorBatteryIconColor = System.getInt(mContext.getContentResolver(), "Biftor_Battery_Icon_Color", mBiftorDefaultColor);
        mBiftorBatteryIconTextColor = System.getInt(mContext.getContentResolver(), "Biftor_Battery_Icon_Text_Color", mBiftorDefaultColor);
        mBiftorBatteryIconLowBattTextColor = System.getInt(mContext.getContentResolver(), "Biftor_Battery_Icon_Text_Low_Color", mBiftorDefaultColor);
        mBiftorBatteryIconChargeBattTextColor = System.getInt(mContext.getContentResolver(), "Biftor_Battery_IconText_Charge_Color", mBiftorDefaultColor);
        mBiftorBatteryIconlocation = System.getInt(mContext.getContentResolver(), "Biftor_BatteryIcon_Location", 1);
        mBiftorNaviBGcolor = System.getInt(mContext.getContentResolver(), "Biftor_Navi_BG_color", -16777216);
        mBiftorNaviBGType = System.getInt(mContext.getContentResolver(), "Biftor_Navi_BG_Type", 1);
        mBiftorEnableGradientNaviBG = System.getInt(mContext.getContentResolver(), "Biftor_Enable_Gradient_Navi_BG", 0);
        mBiftorNaviGradientColor1 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color1_Navi_BG", -1);
        mBiftorNaviGradientColor2 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color2_Navi_BG", -16777216);
        mBiftorNaviGradientColor3 = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Color3_Navi_BG", -1);
        mBiftorNaviGradientBackGroundType = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Navi_BG_Type", 1);
        mBiftorNaviGradientBackGroundModel = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Model_Navi_BG_Type", 0);
        mBiftorNaviGradientBackGroundRadius = System.getInt(mContext.getContentResolver(), "Biftor_Gradient_Radius_Navi_BG", 360);
        mBiftorNaviGradientBackGroundCornerRadius = System.getInt(mContext.getContentResolver(), "Biftor_Corner_Radius_Navi_BG", 0);
        mBiftorNaviGradientEnable3Color = System.getInt(mContext.getContentResolver(), "Biftor_Enable_Gradient_3Color_Navi_BG", 0);
        NaviBackgroundString = System.getString(mContext.getContentResolver(), "Biftor_Navigation_bar_BG");
        mBiftortoggleNaviwallpapercolor = System.getInt(mContext.getContentResolver(), "Biftor_toggle_Naviwallpaper_color", 0);
        mBiftorNaviwallpapercolor = System.getInt(mContext.getContentResolver(), "Biftor_Naviwallpaper_color", 153);
        mBiftorEnableDropDownSlideShow = System.getInt(mContext.getContentResolver(), "Biftor_Enable_DropDownSlideShow_BG", 0);
        mBiftorDropDownSlideShowWallpaper = System.getString(mContext.getContentResolver(), "Biftor_DropDown_BG_SlideShow_Wallpapers");
        mBiftorDropDownSlideShowAnimationType = System.getInt(mContext.getContentResolver(), "Biftor_DropDownSlideShow_BG_Anim_Type", 1);
        mBiftorDropDownSlideShowAnimationDuration = System.getInt(mContext.getContentResolver(), "Biftor_DropDownSlideShow_BG_Anim_Duration", 3000);
        mBiftorEnableDropDownSlideShowEffect = System.getInt(mContext.getContentResolver(), "Biftor_Enable_DropDownSlideShow_Effect", 0);
        mBiftorDropDownSlideShowEffectWallpaper = System.getString(mContext.getContentResolver(), "Biftor_DropDown_SlideShow_Effect_Wallpapers");
        mBiftorDropDownSlideShowEffectAnimationType = System.getInt(mContext.getContentResolver(), "Biftor_DropDownSlideShow_Effect_Anim_Type", 1);
        mBiftorDropDownSlideShowEffectAnimationDuration = System.getInt(mContext.getContentResolver(), "Biftor_DropDownSlideShow_Effect_Anim_Duration", 3000);
        mBiftorDropDownSlideShowEffectPlayAnimationButtonColor = System.getInt(mContext.getContentResolver(), "Biftor_DropDownSlideShow_play_BTN_Color", mBiftorDefaultColor);
        mBiftorEnableDropDownSlideShowEffectFullScreen = System.getInt(mContext.getContentResolver(), "Biftor_Enable_DropDownSlideShow_FullScreen", 1);
        mBiftorDropDownSlideShowEffectScreenOn = System.getInt(mContext.getContentResolver(), "Biftor_Enable_DropDownSlideShow_Keep_ScreenOn", 1);
        mBiftorEnableDropDownSlideShowEffectMusic = System.getInt(mContext.getContentResolver(), "Biftor_Enable_DropDownSlideShow_Effect_Music", 1);
        mBiftorDropDownSlideShowEffectMusic = System.getString(mContext.getContentResolver(), "Biftor_DropDownSlideShow_Effect_Music");
        mBiftorEnableLoopDropDownSlideShowEffectMusic = System.getInt(mContext.getContentResolver(), "Biftor_Enable_DropDownSlideShow_Effect_Music_Loop", 1);
    }
}
